name: jest Tests
on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.10.0]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{matrix.node-version}}
    - name: cd app
      run: cd APP
    - name: npm install
      run: npm install 
    - name: api
      run: node API/src/app
    - name: teste
      run: npm test